fixed the animation of the flashcard
daancs/AppStoreEthics pull request #8
Opened 2023-03-24 12:14 UTC by KristianssonSteffanie

2023-03-24 12:59 UTC, daancs requested changes

2023-03-24 12:59 UTC, daancs commented on src/components/Flashcard.tsx
> +            <div className='h-[650px] w-[450px] [perspective:1000px] hover:cursor-pointer transition-all ease-in-out duration-500 hover:scale-105'>
just fix height and width to a responsive page

2023-03-25 17:06 UTC, bckert approved these changes
Dadis comments seem fixed

2023-03-25 17:33 UTC, williamProgrammerar approved these changes

2023-03-27 11:28 UTC, daancs commented on src/components/Flashcard.tsx
> +        console.log(flip);
Remove comment

2023-03-27 11:46 UTC, merged